version: 1

sources:
  - name: kdrama

models:
  - name: kdrama_reviews
    description: "{{ doc('kdrama_reviews') }}"
    columns:
      - name: drama_name
        description: "{{ doc('drama_name') }}"

      - name: screenwriter
        description: "{{ doc('screenwriter') }}"

      - name: type
        description: "{{ doc('type') }}"
        tests:
          - not_null
          - is_not_drama

      - name: tot_eps
        description: "{{ doc('tot_eps') }}"

      - name: duration
        description: "{{ doc('duration') }}"

      - name: rank
        description: "{{ doc('rank') }}"

      - name: story_score
        description: "{{ doc('story_score') }}"

      - name: acting_cast_score
        description: "{{ doc('acting_cast_score') }}"

      - name: music_score
        description: "{{ doc('music_score') }}"

      - name: rewatch_value_score
        description: "{{ doc('rewatch_value_score') }}"
        
      - name: overall_score
        description: "{{ doc('overall_score') }}"